# Generated by Django 4.0.6 on 2022-08-08 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thread',
            new_name='Post',
        ),
    ]
