# Generated by Django 4.0.6 on 2022-07-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_author',
        ),
    ]
