# Generated by Django 4.0.6 on 2022-07-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_post_board_alter_post_post_text_alter_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent_post_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='board',
            field=models.CharField(max_length=5),
        ),
    ]
